unit Constants;

interface

const
  // Role IDs – should match seed data
  ROLE_ADMIN = 1;
  ROLE_PHARMACIST = 2;
  ROLE_CASHIER = 3;

  // Audit actions
  AUDIT_LOGIN = 'LOGIN';
  AUDIT_LOGOUT = 'LOGOUT';
  AUDIT_USER_CREATE = 'USER_CREATE';
  AUDIT_USER_UPDATE = 'USER_UPDATE';
  AUDIT_USER_DELETE = 'USER_DELETE';
  AUDIT_MEDICINE_CREATE = 'MEDICINE_CREATE';
  AUDIT_MEDICINE_UPDATE = 'MEDICINE_UPDATE';
  AUDIT_MEDICINE_DELETE = 'MEDICINE_DELETE';
  AUDIT_PURCHASE_CREATE = 'PURCHASE_CREATE';
  AUDIT_PURCHASE_UPDATE = 'PURCHASE_UPDATE';
  AUDIT_PURCHASE_DELETE = 'PURCHASE_DELETE';
  AUDIT_DISPENSE = 'DISPENSE';
  AUDIT_INVENTORY_ADJUST = 'INVENTORY_ADJUST';
  AUDIT_EXPIRY_ALERT = 'EXPIRY_ALERT';
  AUDIT_LOW_STOCK_ALERT = 'LOW_STOCK_ALERT';

  // Stock movement types (for inventory adjustment)
  STOCK_IN = 'IN';
  STOCK_OUT = 'OUT';
  STOCK_ADJUST = 'ADJUST';

implementation

end.